-- ЧАСТИНА 1: Очистка + Рівні + Картки
TRUNCATE TABLE card_responses CASCADE;
TRUNCATE TABLE game_sessions CASCADE;
TRUNCATE TABLE card_option_set_links CASCADE;
TRUNCATE TABLE card_options CASCADE;
TRUNCATE TABLE card_option_sets CASCADE;
TRUNCATE TABLE card_properties CASCADE;
TRUNCATE TABLE card_relations CASCADE;
TRUNCATE TABLE game_cards CASCADE;
TRUNCATE TABLE game_levels CASCADE;
TRUNCATE TABLE user_brands CASCADE;
TRUNCATE TABLE user_profiles CASCADE;
TRUNCATE TABLE user_settings CASCADE;
TRUNCATE TABLE users CASCADE;

-- РІВНІ ГРИ
INSERT INTO public.game_levels (id, name, description, "order", color, icon, created_at, updated_at) VALUES ('soul', 'Душа бренду', 'Знайдіть свою місію, цінності та історію бренду', 1, '#e11d48', 'Heart', '2025-08-18 18:55:55.984716', '2025-08-18 18:55:55.984716');
INSERT INTO public.game_levels (id, name, description, "order", color, icon, created_at, updated_at) VALUES ('mind', 'Розум бренду', 'Визначте стратегію, позиціонування та аудиторію', 2, '#2563eb', 'Brain', '2025-08-18 18:55:55.984716', '2025-08-18 18:55:55.984716');
INSERT INTO public.game_levels (id, name, description, "order", color, icon, created_at, updated_at) VALUES ('body', 'Тіло бренду', 'Створіть продукти, канали та візуальний стиль', 3, '#16a34a', 'Layers', '2025-08-18 18:55:55.984716', '2025-08-18 18:55:55.984716');

-- КАРТКИ ГРИ
INSERT INTO public.game_cards (id, level_id, title, description, short_description, hint, type, difficulty, estimated_time, required, position_x, position_y, validation, rewards, created_at, updated_at, validation_rules) VALUES ('soul-start', 'soul', 'Початок подорожі', 'Ласкаво просимо до гри "Душа бренду"! Готові розкрити справжню сутність вашого бренду?', 'Початок пригоди', NULL, 'info', 'easy', 2, true, 1, 100, '{}', '{"xp": 50, "unlocks": ["soul-values"]}', '2025-08-18 18:56:08.462098', '2025-08-23 09:47:14.085', NULL);
INSERT INTO public.game_cards (id, level_id, title, description, short_description, hint, type, difficulty, estimated_time, required, position_x, position_y, validation, rewards, created_at, updated_at, validation_rules) VALUES ('body-channels', 'body', 'Канали комунікації', 'Через які канали ви будете спілкуватися з аудиторією?', 'Виберіть канали', NULL, 'values', 'medium', 10, true, 7, 700, '{"minSelections": 1}', '{"xp": 150, "unlocks": ["body-visual"]}', '2025-08-18 18:56:31.81019', '2025-09-11 09:53:19.941', NULL);
INSERT INTO public.game_cards (id, level_id, title, description, short_description, hint, type, difficulty, estimated_time, required, position_x, position_y, validation, rewards, created_at, updated_at, validation_rules) VALUES ('soul-values', 'soul', 'Цінності бренду', 'Оберіть 3-5 найважливіших цінностей, які визначають ваш бренд', 'Визначте цінності', NULL, 'values', 'medium', 10, true, 2, 150, '{"minSelections": 3, "maxSelections": 5}', '{"xp": 100, "unlocks": ["soul-mission"]}', '2025-08-18 18:56:08.462098', '2025-08-23 09:47:14.109', NULL);
INSERT INTO public.game_cards (id, level_id, title, description, short_description, hint, type, difficulty, estimated_time, required, position_x, position_y, validation, rewards, created_at, updated_at, validation_rules) VALUES ('mind-positioning', 'mind', 'Позиціонування бренду', 'Як ви позиціонуєте свій бренд на ринку? Чим відрізняєтеся?', 'Створіть позиціонування', NULL, 'text', 'medium', 20, true, 7, 450, '{"minLength": 80}', '{"xp": 175, "unlocks": ["mind-archetype"]}', '2025-08-18 18:56:19.402755', '2025-08-23 09:47:01.986', NULL);
INSERT INTO public.game_cards (id, level_id, title, description, short_description, hint, type, difficulty, estimated_time, required, position_x, position_y, validation, rewards, created_at, updated_at, validation_rules) VALUES ('soul-purpose', 'soul', 'Мета бренду', 'Яка глибша мета вашого бренду? Як ви хочете змінити світ?', 'Визначте мету', NULL, 'reflection', 'hard', 25, true, 9, 300, '{"minLength": 80}', '{"xp": 250, "badges": ["soul_complete"], "unlocks": ["mind-start"]}', '2025-08-18 18:56:08.462098', '2025-08-23 09:47:01.801', NULL);
INSERT INTO public.game_cards (id, level_id, title, description, short_description, hint, type, difficulty, estimated_time, required, position_x, position_y, validation, rewards, created_at, updated_at, validation_rules) VALUES ('soul-mission', 'soul', 'Місія бренду', 'Опишіть місію вашого бренду в 1-2 реченнях. Для чого існує ваш бренд?', 'Створіть місію', NULL, 'text', 'medium', 15, true, 5, 200, '{"minLength": 50, "maxLength": 200}', '{"xp": 150, "unlocks": ["soul-story"]}', '2025-08-18 18:56:08.462098', '2025-08-23 09:47:01.706', NULL);
INSERT INTO public.game_cards (id, level_id, title, description, short_description, hint, type, difficulty, estimated_time, required, position_x, position_y, validation, rewards, created_at, updated_at, validation_rules) VALUES ('body-visual', 'body', 'Візуальний стиль', 'Опишіть візуальний стиль вашого бренду - кольори, форми, настрій', 'Створіть стиль', NULL, 'text', 'hard', 20, true, 8, 750, '{"minLength": 80}', '{"xp": 175, "unlocks": ["body-actions"]}', '2025-08-18 18:56:31.81019', '2025-09-11 09:53:19.965', NULL);
INSERT INTO public.game_cards (id, level_id, title, description, short_description, hint, type, difficulty, estimated_time, required, position_x, position_y, validation, rewards, created_at, updated_at, validation_rules) VALUES ('soul-impact', 'soul', 'Вплив на Світ', 'Як ваш бренд змінює світ на краще?', 'Позитивний вплив бренду', 'Подумайте про конкретні зміни, які ваш бренд приносить у світ', 'text', 'medium', 3, true, 6, 200, NULL, '{"xp": 15}', '2025-08-18 20:14:42.059193', '2025-08-23 09:47:01.729', NULL);
INSERT INTO public.game_cards (id, level_id, title, description, short_description, hint, type, difficulty, estimated_time, required, position_x, position_y, validation, rewards, created_at, updated_at, validation_rules) VALUES ('body-actions', 'body', 'План дій', 'Які конкретні дії ви плануєте реалізувати найближчим часом?', 'Складіть план', NULL, 'values', 'hard', 30, true, 9, 800, '{"minSelections": 3, "maxSelections": 8}', '{"xp": 300, "badges": ["body_complete", "brand_master"]}', '2025-08-18 18:56:31.81019', '2025-09-11 09:53:19.989', NULL);
INSERT INTO public.game_cards (id, level_id, title, description, short_description, hint, type, difficulty, estimated_time, required, position_x, position_y, validation, rewards, created_at, updated_at, validation_rules) VALUES ('mind-target', 'mind', 'Цільова Аудиторія', 'Опишіть вашу ідеальну цільову аудиторію: хто ці люди, що їх цікавить, які у них потреби?', 'Опишіть цільову аудиторію', 'Подумайте про демографію, психографію та потреби', 'text', 'medium', 3, true, 2, 100, NULL, '{"xp": 15}', '2025-08-18 20:20:52.410779', '2025-08-23 09:47:01.872', '{"minLength": 50, "maxLength": 300}');
INSERT INTO public.game_cards (id, level_id, title, description, short_description, hint, type, difficulty, estimated_time, required, position_x, position_y, validation, rewards, created_at, updated_at, validation_rules) VALUES ('mind-archetype', 'mind', 'Архетип бренду', 'Оберіть архетип, який найкраще описує характер вашого бренду', 'Оберіть архетип', NULL, 'archetype', 'medium', 10, true, 8, 500, '{"minSelections": 1, "maxSelections": 3}', '{"xp": 150, "unlocks": ["mind-promise"]}', '2025-08-18 18:56:19.402755', '2025-08-23 09:47:02.009', NULL);
INSERT INTO public.game_cards (id, level_id, title, description, short_description, hint, type, difficulty, estimated_time, required, position_x, position_y, validation, rewards, created_at, updated_at, validation_rules) VALUES ('soul-emotion', 'soul', 'Емоційна глибина', 'Яка глибинна потреба людей рухає вашим брендом?', 'Емоційний звязок', 'Подумайте про глибинні емоції', 'text', 'medium', 3, true, 2, 3, '{"minLength": 50}', '{"xp": 15}', '2025-08-18 19:34:53.349419', '2025-08-23 09:47:01.639', NULL);
INSERT INTO public.game_cards (id, level_id, title, description, short_description, hint, type, difficulty, estimated_time, required, position_x, position_y, validation, rewards, created_at, updated_at, validation_rules) VALUES ('soul-story', 'soul', 'Історія бренду', 'Розкажіть унікальну історію вашого бренду. Що вас надихнуло створити цей бренд?', 'Розкажіть історію', NULL, 'text', 'hard', 20, true, 7, 250, '{"minLength": 100, "maxLength": 500}', '{"xp": 200, "unlocks": ["soul-purpose"]}', '2025-08-18 18:56:08.462098', '2025-08-23 09:47:01.757', NULL);
INSERT INTO public.game_cards (id, level_id, title, description, short_description, hint, type, difficulty, estimated_time, required, position_x, position_y, validation, rewards, created_at, updated_at, validation_rules) VALUES ('mind-audience', 'mind', 'Цільова аудиторія', 'Опишіть детально вашу ідеальну цільову аудиторію', 'Визначте аудиторію', NULL, 'text', 'medium', 15, true, 5, 400, '{"minLength": 100}', '{"xp": 125, "unlocks": ["mind-positioning"]}', '2025-08-18 18:56:19.402755', '2025-08-23 09:47:01.941', NULL);
INSERT INTO public.game_cards (id, level_id, title, description, short_description, hint, type, difficulty, estimated_time, required, position_x, position_y, validation, rewards, created_at, updated_at, validation_rules) VALUES ('mind-promise', 'mind', 'Обіцянка бренду', 'Яку головну обіцянку ваш бренд дає клієнтам?', 'Сформулюйте обіцянку', NULL, 'text', 'hard', 25, true, 9, 550, '{"minLength": 50, "maxLength": 150}', '{"xp": 200, "badges": ["mind_complete"], "unlocks": ["body-start"]}', '2025-08-18 18:56:19.402755', '2025-08-23 09:47:02.032', NULL);
INSERT INTO public.game_cards (id, level_id, title, description, short_description, hint, type, difficulty, estimated_time, required, position_x, position_y, validation, rewards, created_at, updated_at, validation_rules) VALUES ('body-start', 'body', 'Втілення бренду', 'Час втілити ваш бренд у реальність через продукти та канали', 'Почнімо втілення', NULL, 'text', 'easy', 5, true, 5, 600, '{"minLength": 20}', '{"xp": 75, "unlocks": ["body-products"]}', '2025-08-18 18:56:31.81019', '2025-09-11 09:53:19.895', NULL);
INSERT INTO public.game_cards (id, level_id, title, description, short_description, hint, type, difficulty, estimated_time, required, position_x, position_y, validation, rewards, created_at, updated_at, validation_rules) VALUES ('body-products', 'body', 'Продукти та послуги', 'Перерахуйте основні продукти чи послуги вашого бренду', 'Опишіть продукти', NULL, 'values', 'medium', 15, true, 6, 650, '{"minSelections": 1, "maxSelections": 10}', '{"xp": 125, "unlocks": ["body-channels"]}', '2025-08-18 18:56:31.81019', '2025-09-11 09:53:19.919', NULL);
INSERT INTO public.game_cards (id, level_id, title, description, short_description, hint, type, difficulty, estimated_time, required, position_x, position_y, validation, rewards, created_at, updated_at, validation_rules) VALUES ('mind-problem', 'mind', 'Проблема Аудиторії', 'Яку головну проблему вашої цільової аудиторії ви вирішуєте?', 'Проблема аудиторії', NULL, 'reflection', 'medium', 3, true, 1, 150, NULL, '{"xp": 15}', '2025-08-19 08:26:06.996982', '2025-08-23 09:47:01.847', NULL);
INSERT INTO public.game_cards (id, level_id, title, description, short_description, hint, type, difficulty, estimated_time, required, position_x, position_y, validation, rewards, created_at, updated_at, validation_rules) VALUES ('mind-start', 'mind', 'Розум Бренду', 'Вітаємо на рівні "Розум Бренду"! Тут ви розробите стратегію та позиціонування вашого бренду. Визначите цільову аудиторію, конкурентів та унікальну цінність пропозицію.', 'Почнімо стратегію', NULL, 'info', 'easy', 5, true, 3, 350, '{"minLength": 20}', '{"xp": 75, "unlocks": ["mind-audience"]}', '2025-08-18 18:56:19.402755', '2025-08-23 09:47:01.896', NULL);
INSERT INTO public.game_cards (id, level_id, title, description, short_description, hint, type, difficulty, estimated_time, required, position_x, position_y, validation, rewards, created_at, updated_at, validation_rules) VALUES ('body-pricing', 'body', 'Ціноутворення', 'Визначте стратегію ціноутворення для вашого бренду', 'Ціноутворення', NULL, 'choice', 'medium', 2, true, 1, 6, '{"minSelections": 1, "maxSelections": 1}', '{"xp": 10}', '2025-08-19 08:59:04.803392', '2025-09-11 09:53:19.8', NULL);
INSERT INTO public.game_cards (id, level_id, title, description, short_description, hint, type, difficulty, estimated_time, required, position_x, position_y, validation, rewards, created_at, updated_at, validation_rules) VALUES ('body-tone', 'body', 'Тон голосу', 'Оберіть тон голосу для комунікації вашого бренду', 'Тон голосу', NULL, 'values', 'medium', 4, true, 2, 7, '{"minSelections": 1, "maxSelections": 2}', '{"xp": 20}', '2025-08-19 08:59:04.803392', '2025-09-11 09:53:19.824', NULL);
INSERT INTO public.game_cards (id, level_id, title, description, short_description, hint, type, difficulty, estimated_time, required, position_x, position_y, validation, rewards, created_at, updated_at, validation_rules) VALUES ('body-metrics', 'body', 'Метрики успіху', 'Оберіть ключові метрики для вимірювання успіху бренду', 'Метрики успіху', NULL, 'values', 'medium', 4, true, 3, 8, '{"minSelections": 2, "maxSelections": 5}', '{"xp": 20}', '2025-08-19 08:59:04.803392', '2025-09-11 09:53:19.848', NULL);
INSERT INTO public.game_cards (id, level_id, title, description, short_description, hint, type, difficulty, estimated_time, required, position_x, position_y, validation, rewards, created_at, updated_at, validation_rules) VALUES ('soul-deep-values', 'soul', 'Глибина Цінностей', 'Розкажіть, як обрані цінності проявляються у вашій щоденній роботі', 'Як живуть цінності', NULL, 'reflection', 'medium', 3, false, 3, 1, NULL, '{"xp": 15}', '2025-08-18 20:47:33.704036', '2025-08-23 09:47:01.661', '{"minLength": 100, "maxLength": 500}');
INSERT INTO public.game_cards (id, level_id, title, description, short_description, hint, type, difficulty, estimated_time, required, position_x, position_y, validation, rewards, created_at, updated_at, validation_rules) VALUES ('mind-solution', 'mind', 'Рішення Проблеми', 'Як саме ваш бренд вирішує цю проблему? Опишіть ваше унікальне рішення.', 'Рішення проблеми', NULL, 'text', 'medium', 3, true, 4, 200, NULL, '{"xp": 15}', '2025-08-19 08:26:06.996982', '2025-08-23 09:47:01.918', NULL);
INSERT INTO public.game_cards (id, level_id, title, description, short_description, hint, type, difficulty, estimated_time, required, position_x, position_y, validation, rewards, created_at, updated_at, validation_rules) VALUES ('mind-benefit', 'mind', 'Основна Вигода', 'Яку головну вигоду отримують клієнти від вашого бренду?', 'Основна вигода', NULL, 'text', 'easy', 3, true, 6, 250, NULL, '{"xp": 15}', '2025-08-19 08:26:06.996982', '2025-08-23 09:47:01.963', NULL);
INSERT INTO public.game_cards (id, level_id, title, description, short_description, hint, type, difficulty, estimated_time, required, position_x, position_y, validation, rewards, created_at, updated_at, validation_rules) VALUES ('body-launch', 'body', 'План запуску', 'Опишіть план запуску вашого бренду', 'План запуску', NULL, 'text', 'medium', 3, true, 4, 9, '{"minLength": 50, "maxLength": 1000}', '{"xp": 15}', '2025-08-19 08:59:04.803392', '2025-09-11 09:53:19.871', NULL);
INSERT INTO public.game_cards (id, level_id, title, description, short_description, hint, type, difficulty, estimated_time, required, position_x, position_y, validation, rewards, created_at, updated_at, validation_rules) VALUES ('body-complete', 'body', 'Вітаємо! Гра завершена', 'Ви успішно створили повну карту вашого бренду. Тепер ви можете переглянути дошку бренду або почати нову гру.', 'Завершення гри', NULL, 'complete', 'easy', 2, true, 10, 10, '{}', '{"xp": 10}', '2025-08-19 09:05:10.002019', '2025-09-11 09:53:20.012', NULL);
INSERT INTO public.game_cards (id, level_id, title, description, short_description, hint, type, difficulty, estimated_time, required, position_x, position_y, validation, rewards, created_at, updated_at, validation_rules) VALUES ('soul-archetype', 'soul', 'Архетип Бренду', 'Який архетип найкраще описує вашу сутність?', 'Виберіть архетип бренду', 'Архетип визначає характер та поведінку вашого бренду', 'archetype', 'hard', 3, true, 3, 300, '{"maxSelections": 3, "minSelections": 1}', '{"xp": 15}', '2025-08-18 20:14:42.059193', '2025-08-23 09:47:14.132', NULL);
